<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        DB::table('TBLUSR')->insert([  'TUUSERIY' => '1' , 'TUUSER' => 'admin' , 'TUNAME' => 'admin' , 'TUPSWD' => '0ebcc77dc72360d0eb8e9504c78d38bd' , 'TUEMID' => '-' , 'TUDEPT' => '-' , 'TUMAIL' => 'admin@admin.com' , 'TUWELC' => '' , 'TUEXPP' => '0' , 'TUEXPD' => '20370209' , 'TUEXPV' => '3' , 'TULGCT' => '915' , 'TULSLI' =>  Date("Y-m-d H:i:s") , 'TULSLO' =>  Date("Y-m-d H:i:s") , 'TUREMK' => '' , 'TURGID' => 'APPSERVER06\Administrator' , 'TURGDT' =>  Date("Y-m-d H:i:s") , 'TUCHID' => 'admin' , 'TUCHDT' =>  Date("Y-m-d H:i:s") , 'TUCHNO' => '15' , 'TUDLFG' => '0' , 'TUDPFG' => '1' , 'TUPTFG' => '0' , 'TUPTCT' => '0' , 'TUPTID' => '' , 'TUPTDT' =>  Date("Y-m-d H:i:s") , 'TUSRCE' => 'Web' , 'TUUSRM' => '' , 'TUITRM' => '' , 'TUCSDT' =>  Date("Y-m-d H:i:s") , 'TUCSID' => 'admin' ]); 

        DB::table('TBLMNU')->insert([   'TMMENUIY' => '1' , 'TMNOMR' => '01' , 'TMGRUP' => '' , 'TMMENU' => 'FILE' , 'TMDESC' => '' , 'TMSCUT' => '' , 'TMACES' => '' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => '' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '2' , 'TMNOMR' => '0101' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'SINTAX LOG FILE' , 'TMDESC' => '' , 'TMSCUT' => 'FIL001' , 'TMACES' => 'VXL' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLSLF' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '3' , 'TMNOMR' => '0102' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'ERROR LOG FILE' , 'TMDESC' => '' , 'TMSCUT' => 'FIL002' , 'TMACES' => 'VXL' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLELF' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '4' , 'TMNOMR' => '0103' , 'TMGRUP' => '' , 'TMMENU' => 'MENU' , 'TMDESC' => '' , 'TMSCUT' => 'FIL003' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLMNU' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '5' , 'TMNOMR' => '0104' , 'TMGRUP' => '' , 'TMMENU' => 'SET USER' , 'TMDESC' => '' , 'TMSCUT' => 'FIL004' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLUSR' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '6' , 'TMNOMR' => '0105' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'COMMENT MENU' , 'TMDESC' => '' , 'TMSCUT' => 'FIL005' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLCMT' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '7' , 'TMNOMR' => '0106' , 'TMGRUP' => '' , 'TMMENU' => 'QUERY ANALYZER' , 'TMDESC' => '' , 'TMSCUT' => 'FIL006' , 'TMACES' => 'VX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'QUERY' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '8' , 'TMNOMR' => '0107' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'LOCK TRANSACTION MENU' , 'TMDESC' => '' , 'TMSCUT' => 'FIL007' , 'TMACES' => 'VDX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLOCK' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '9' , 'TMNOMR' => '0108' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'PROCESS BATCH LOG FILE' , 'TMDESC' => '' , 'TMSCUT' => 'FIL008' , 'TMACES' => 'VXL' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLPLF' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '10' , 'TMNOMR' => '0109' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'MAINTAINCE LOGFILE' , 'TMDESC' => '' , 'TMSCUT' => 'FIL009' , 'TMACES' => 'VXL' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLHSS' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '11' , 'TMNOMR' => '02' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER' , 'TMDESC' => '' , 'TMSCUT' => '' , 'TMACES' => '' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => '' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '12' , 'TMNOMR' => '0205' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER SYSTEM' , 'TMDESC' => '' , 'TMSCUT' => '' , 'TMACES' => '' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => '' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '13' , 'TMNOMR' => '020505' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER TABLE PARAMETER' , 'TMDESC' => '' , 'TMSCUT' => 'SYS005' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLPRM' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '14' , 'TMNOMR' => '020510' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER TABLE DESCRIPTION *' , 'TMDESC' => '' , 'TMSCUT' => 'SYS010' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLDSC' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '15' , 'TMNOMR' => '020515' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER TABLE SYSTEM *' , 'TMDESC' => '' , 'TMSCUT' => 'SYS015' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLSYS' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '16' , 'TMNOMR' => '020520' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER TABLE ERROR MESSAGE' , 'TMDESC' => '' , 'TMSCUT' => 'SYS020' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'TBLSMG' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '17' , 'TMNOMR' => '0210' , 'TMGRUP' => '' , 'TMMENU' => 'MASTER GENERAL' , 'TMDESC' => '' , 'TMSCUT' => '' , 'TMACES' => '' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => '' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '18' , 'TMNOMR' => '021005' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'MASTER PROFIT' , 'TMDESC' => '' , 'TMSCUT' => 'GEN005' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'MMPROF' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '19' , 'TMNOMR' => '021010' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'MASTER COST CENTER' , 'TMDESC' => '' , 'TMSCUT' => 'GEN010' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'MMCTCR' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '20' , 'TMNOMR' => '021015' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'MASTER CATEGORY' , 'TMDESC' => '' , 'TMSCUT' => 'GEN015' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'MMCATG' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '21' , 'TMNOMR' => '021020' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'MASTER SUB CATEGORY' , 'TMDESC' => '' , 'TMSCUT' => 'GEN020' , 'TMACES' => 'VAEDLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'MMCATS' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '22' , 'TMNOMR' => '03' , 'TMGRUP' => '' , 'TMMENU' => 'TRANSACTION' , 'TMDESC' => '' , 'TMSCUT' => '' , 'TMACES' => '' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => '' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => '' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'sql.edison.gunawan' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '23' , 'TMNOMR' => '0305' , 'TMGRUP' => '' , 'TMMENU' => 'BKK / BPU' , 'TMDESC' => '' , 'TMSCUT' => 'TRS005' , 'TMACES' => 'VAEDLPX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'BBHEAD' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '24' , 'TMNOMR' => '04' , 'TMGRUP' => '' , 'TMMENU' => 'INFORMATION' , 'TMDESC' => '' , 'TMSCUT' => '' , 'TMACES' => '' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => '' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 
        DB::table('TBLMNU')->insert([   'TMMENUIY' => '25' , 'TMNOMR' => '0405' , 'TMGRUP' => 'FORM01' , 'TMMENU' => 'INFORMATON BKK / BPU' , 'TMDESC' => '' , 'TMSCUT' => 'INF005' , 'TMACES' => 'VLX' , 'TMBCDT' => '99' , 'TMFWDT' => '99' , 'TMURLW' => 'INF_BBHEAD' , 'TMSYFG' => 'E' , 'TMGRID' => 'SysAdmin'  , 'TMREMK' => '' , 'TMRGID' => 'SysAdmin', 'TMRGDT' => Date("Y-m-d H:i:s")  , 'TMCHID' => 'SysAdmin'  , 'TMCHDT' => Date("Y-m-d H:i:s")  , 'TMCHNO' => 0  , 'TMDLFG' => '0' , 'TMDPFG' => '1' , 'TMSRCE' => 'Web' , 'TMUSRM' => '' , 'TMITRM' => '' , 'TMCSDT' => Date("Y-m-d H:i:s")  , 'TMCSID' => 'admin' ]); 

        DB::table('TBLNOR')->insert([  'TNTABL' => 'TBLMNU' , 'TNNOUR' => '25' , 'TNREMK' => '' , 'TNSRCE' => '1' , 'TNRGID' => 'SysAdmin', 'TNRGDT' => Date("Y-m-d H:i:s")  , 'TNCHID' => 'SysAdmin'  , 'TNCHDT' => Date("Y-m-d H:i:s")  , 'TNCHNO' => 0  , 'TNDLFG' => '0' , 'TNDPFG' => '1' , 'TNSRCE' => 'Web' , 'TNUSRM' => '' , 'TNITRM' => '' , 'TNCSDT' => Date("Y-m-d H:i:s")  , 'TNCSID' => 'admin' ]); 
        DB::table('TBLNOR')->insert([  'TNTABL' => 'TBLUSR' , 'TNNOUR' => '1' , 'TNREMK' => '' , 'TNSRCE' => '1' , 'TNRGID' => 'SysAdmin', 'TNRGDT' => Date("Y-m-d H:i:s")  , 'TNCHID' => 'SysAdmin'  , 'TNCHDT' => Date("Y-m-d H:i:s")  , 'TNCHNO' => 0  , 'TNDLFG' => '0' , 'TNDPFG' => '1' , 'TNSRCE' => 'Web' , 'TNUSRM' => '' , 'TNITRM' => '' , 'TNCSDT' => Date("Y-m-d H:i:s")  , 'TNCSID' => 'admin' ]); 
        DB::table('TBLNOR')->insert([  'TNTABL' => 'TBLUAM' , 'TNNOUR' => '1' , 'TNREMK' => '' , 'TNSRCE' => '1' , 'TNRGID' => 'SysAdmin', 'TNRGDT' => Date("Y-m-d H:i:s")  , 'TNCHID' => 'SysAdmin'  , 'TNCHDT' => Date("Y-m-d H:i:s")  , 'TNCHNO' => 0  , 'TNDLFG' => '0' , 'TNDPFG' => '1' , 'TNSRCE' => 'Web' , 'TNUSRM' => '' , 'TNITRM' => '' , 'TNCSDT' => Date("Y-m-d H:i:s")  , 'TNCSID' => 'admin' ]); 


        DB::table('TBLDSC')->insert([  'TDDSCD' => 'DSPLY' , 'TDDSNM' => 'DISPLAY' , 'TDLGTH' => '1' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DSPLY' , 'TSSYCD' => '0' , 'TSSYNM' => 'Not Display' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DSPLY' , 'TSSYCD' => '1' , 'TSSYNM' => 'Display' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
                
        DB::table('TBLDSC')->insert([  'TDDSCD' => 'MODE' , 'TDDSNM' => 'MODE HAK AKSES' , 'TDLGTH' => '1' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'A' , 'TSSYNM' => 'ADD' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '2' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'D' , 'TSSYNM' => 'DELETE' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '4' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'E' , 'TSSYNM' => 'EDIT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '3' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'L' , 'TSSYNM' => 'VIEW LIST' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '5' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'P' , 'TSSYNM' => 'PRINT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '7' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'R' , 'TSSYNM' => 'Approval' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '6' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'V' , 'TSSYNM' => 'VIEW' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '1' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'MODE' , 'TSSYCD' => 'X' , 'TSSYNM' => 'EXPORT TO EXCEL' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 

        DB::table('TBLDSC')->insert([  'TDDSCD' => 'ET' , 'TDDSNM' => 'ERROR TYPE' , 'TDLGTH' => '2' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'ET' , 'TSSYCD' => 'SP' , 'TSSYNM' => 'STORE PROCEDURE' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'ET' , 'TSSYCD' => 'AP' , 'TSSYNM' => 'APPLICATION' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]); 


        DB::table('TBLDSC')->insert([  'TDDSCD' => 'DEPT' , 'TDDSNM' => 'DEPARTNENT' , 'TDLGTH' => '6' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'ACC001' , 'TSSYNM' => 'ACCOUNTING' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'AUD001' , 'TSSYNM' => 'INTERNAL AUDIT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'COR001' , 'TSSYNM' => 'CORPORATE' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'COS001' , 'TSSYNM' => 'COST CONTROLLER' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'DIR001' , 'TSSYNM' => 'DIREKSI' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'DUM001' , 'TSSYNM' => 'DUMP TRUCK - FACTORY 1' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'ELE001' , 'TSSYNM' => 'ELECTRONIC DATA PROCESSING' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'ENG001' , 'TSSYNM' => 'ENGINEERING' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'EXP001' , 'TSSYNM' => 'EXPORT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'FIN001' , 'TSSYNM' => 'FINANCE' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'HEA001' , 'TSSYNM' => 'HEALTH AND SAFETY ENVIRONMENT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'HRD001' , 'TSSYNM' => 'HUMAN & RESOURCES DEVELOPMENT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'IMP001' , 'TSSYNM' => 'IMPORT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'INF001' , 'TSSYNM' => 'INFORMATION TECHNOLOGY' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'KEP001' , 'TSSYNM' => 'KEPALA PABRIK' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'LAB001' , 'TSSYNM' => 'LABORATORIUM' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'LEG001' , 'TSSYNM' => 'LEGAL' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'MAR001' , 'TSSYNM' => 'MARKETING' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'MRM001' , 'TSSYNM' => 'MANAGEMENT REPRESENTATIVE' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'MTC001' , 'TSSYNM' => 'MAINTENANCE' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'NEW001' , 'TSSYNM' => 'NEW PRODUCT DEVELOPMENT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'PER001' , 'TSSYNM' => 'PERSONALIA' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'PPI001' , 'TSSYNM' => 'PPIC' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'PRE001' , 'TSSYNM' => 'PRESS SHOP' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'PRO001' , 'TSSYNM' => 'PRODUCTION' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'PUR001' , 'TSSYNM' => 'PURCHASING' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'QUA001' , 'TSSYNM' => 'QUALITY ASSURANCE / CONTROL' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'SLS001' , 'TSSYNM' => 'SALES' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'TPD001' , 'TSSYNM' => 'TPD' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DEPT' , 'TSSYCD' => 'UMU001' , 'TSSYNM' => 'UMUM' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  

        DB::table('TBLDSC')->insert([  'TDDSCD' => 'CURR' , 'TDDSNM' => 'CURRENCY' , 'TDLGTH' => '3' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'EUR' , 'TSSYNM' => 'EURO' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'GBP' , 'TSSYNM' => 'GBP' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'IDR' , 'TSSYNM' => 'RUPIAH' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'MYR' , 'TSSYNM' => 'RINGGIT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'RMB' , 'TSSYNM' => 'RENMINBI' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'SGD' , 'TSSYNM' => 'SIN DOLLAR' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'USD' , 'TSSYNM' => 'US DOLLAR' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'CURR' , 'TSSYCD' => 'YEN' , 'TSSYNM' => 'YEN' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  

        DB::table('TBLDSC')->insert([  'TDDSCD' => 'DIVI' , 'TDDSNM' => 'DIVISION' , 'TDLGTH' => '3' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'ADR' , 'TSSYNM' => 'AUTO DIESEL RADIATOR, CV' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'AIP' , 'TSSYNM' => 'ADRINDO INTIPERKASA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'APP' , 'TSSYNM' => 'ADRINDO PERKASA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'DBB' , 'TSSYNM' => 'DINAMIKAJAYA BUMIPERSADA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'HAM' , 'TSSYNM' => 'HYDRAXLE PERKASA - AM, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'HDC' , 'TSSYNM' => 'HYDRAXLE PERKASA - DC, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'HSC' , 'TSSYNM' => 'HYDRAXLE PERKASA - SC, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'HSY' , 'TSSYNM' => 'HYDRAXLE PERKASA - SY, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'HYP' , 'TSSYNM' => 'HYDRAXLE PERKASA - DT, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'IKY' , 'TSSYNM' => 'IKUYO INDONESIA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'MD0' , 'TSSYNM' => 'MANGATUR DHARMA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'MSK' , 'TSSYNM' => 'MANGATUR SETIA KAWAN, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'PAI' , 'TSSYNM' => 'PRIMA AUTO INDONESIA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'PHI' , 'TSSYNM' => 'PRIMA HONEYCOMB INTERNATIONAL, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'PJM' , 'TSSYNM' => 'PANATA JAYA MANDIRI, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'PTC' , 'TSSYNM' => 'PRAPAT TUNGGAL CIPTA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'RUP' , 'TSSYNM' => 'RUBBERINDO UNGGUL PERKASA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'SSP' , 'TSSYNM' => 'SELAMAT SEMPANA PERKASA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'SSS' , 'TSSYNM' => 'SELAMAT SEMPURNA TBK, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'TES' , 'TSSYNM' => 'COMPANY TESTING' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'DIVI' , 'TSSYCD' => 'ZXA' , 'TSSYNM' => 'ZX AUTO INDONESIA, PT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  

        DB::table('TBLDSC')->insert([  'TDDSCD' => 'LOCA' , 'TDDSNM' => 'LOCATION' , 'TDLGTH' => '3' , 'TDREMK' => '' , 'TDRGID' => 'APPSERVER06\Administrator' , 'TDRGDT' =>  Date("Y-m-d H:i:s") , 'TDCHID' => 'APPSERVER06\Administrator' , 'TDCHDT' =>  Date("Y-m-d H:i:s") , 'TDCHNO' => '0' , 'TDDLFG' => '0' , 'TDDPFG' => '1' , 'TDPTFG' => '0' , 'TDPTCT' => '0' , 'TDPTID' => '' , 'TDPTDT' =>  Date("Y-m-d H:i:s") , 'TDSRCE' => '' , 'TDUSRM' => '' , 'TDITRM' => '' , 'TDCSDT' =>  Date("Y-m-d H:i:s") , 'TDCSID' => 'APPSERVER06\Administrator' ]); 
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'ALL' , 'TSSYNM' => 'ALL' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'ATC' , 'TSSYNM' => 'ADRTC' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'EXP' , 'TSSYNM' => 'EXP TGR' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'IMP' , 'TSSYNM' => 'IMPORT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'KPK' , 'TSSYNM' => 'KAPUK' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'MKR' , 'TSSYNM' => 'MAKASSAR' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'PLT' , 'TSSYNM' => 'PLUIT' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'TGR' , 'TSSYNM' => 'TANGERANG' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'XKP' , 'TSSYNM' => 'EXP KPK' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  
        DB::table('TBLSYS')->insert([  'TSDSCD' => 'LOCA' , 'TSSYCD' => 'YKR' , 'TSSYNM' => 'KARANG ANYER' , 'TSSYV1' => '0.0000000000' , 'TSSYV2' => '0.0000000000' , 'TSSYV3' => '0.0000000000' , 'TSSYT1' => '' , 'TSSYT2' => '' , 'TSSYT3' => '8' , 'TSLSV1' => '' , 'TSLSV2' => '' , 'TSLSV3' => '' , 'TSLST1' => '' , 'TSLST2' => '' , 'TSLST3' => '' , 'TSREMK' => '' , 'TSRGID' => 'System' , 'TSRGDT' =>  Date("Y-m-d H:i:s") , 'TSCHID' => 'System' , 'TSCHDT' =>  Date("Y-m-d H:i:s") , 'TSCHNO' => '0' , 'TSDLFG' => '0' , 'TSDPFG' => '1' , 'TSPTFG' => '0' , 'TSPTCT' => '0' , 'TSPTID' => '' , 'TSPTDT' =>  Date("Y-m-d H:i:s") , 'TSSRCE' => '' , 'TSUSRM' => '' , 'TSITRM' => '' , 'TSCSDT' =>  Date("Y-m-d H:i:s") , 'TSCSID' => 'System' ]);  


        // $driver = config("database.connections.{$connection}.driver");
        $driver = DB::connection()->getConfig("driver");
        if ($driver=="sqlsrv") {
            DB::insert("
                    Insert Into TBLUAM (
                         TAUSERIY, TAMENUIY, TAACES, TAREMK
                        ,TARGID,TARGDT,TACHID,TACHDT,TACHNO,TADLFG,TADPFG
                        ,TASRCE,TAUSRM,TAITRM,TACSDT,TACSID )
                    Select 
                    TUUSERIY TAUSERIY,TMMENUIY TAMENUIY,TMACES TAACES, 'Pertama' TAREMK
                    ,'FirstTime' TARGID, GetDate() TARGDT,'FirstTime' TACHID, GetDate() TACHDT, 0 TACHNO
                    ,0 TADLFG, 1 TADPFG
                    ,'FirstTime' TASRCE, '' TAUSRM, '' TAITRM,GetDate() TACSDT,'FirstTime' TACSID
                    From TBLMNU
                    Left Join TBLUSR On 1 = 1

                    UpDate TBLNOR Set TNNOUR = (Select Max(TMMENUIY) From TBLMNU) Where TNTABL = 'TBLMNU'

                "); 
        } else if ($driver=="mysql") {
            DB::insert("
                    Insert Into TBLUAM (
                         TAUSERIY, TAMENUIY, TAACES, TAREMK
                        ,TARGID,TARGDT,TACHID,TACHDT,TACHNO,TADLFG,TADPFG
                        ,TASRCE,TAUSRM,TAITRM,TACSDT,TACSID )
                    Select 
                    TUUSERIY TAUSERIY,TMMENUIY TAMENUIY,TMACES TAACES, 'Pertama' TAREMK
                    ,'FirstTime' TARGID, Now() TARGDT,'FirstTime' TACHID, Now() TACHDT, 0 TACHNO
                    ,0 TADLFG, 1 TADPFG
                    ,'FirstTime' TASRCE, '' TAUSRM, '' TAITRM, Now() TACSDT,'FirstTime' TACSID
                    From TBLMNU
                    Left Join TBLUSR On 1 = 1;
                "); 
            DB::insert("
                    UpDate TBLNOR 
                    inner join (Select Max(TMMENUIY) NOUR From TBLMNU) As A On 1 = 1
                    Set TNNOUR = NOUR Where TNTABL = 'TBLMNU';
                ");             
        }


    }
}
